spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/boot
    username: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml